spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_management_db
    username: root
    password: password123
  application:
    name: task-management-app
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MYSQLDialect
        format_sql: true
  devtools:
    restart:
      enabled: true